use_frameworks!

platform :ios, '9.0'

target 'GracefulTSwifter_Example' do
  pod 'GracefulTSwifter', :path => '../'

  target 'GracefulTSwifter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
